abbr -a 'g git'
abbr -a 'l ls'
abbr -a 'ta tmux attach'
abbr -a 'gc git commit'
abbr -a 'tigs tig status'
abbr -a 'nv nvim'
abbr -a 'nt npm test'
abbr -a 'gaa git add --all .'
abbr -a 'ga git add'
abbr -a 'gg ag'
abbr -a 'gpr git pull --rebase'
abbr -a 'cask brew cask'
abbr -a 'vim nvim'
abbr -a 'gcm git commit -m'
abbr -a 'd dirh'
