abbr -a '1 prevd'
abbr -a '2 nextd'
abbr -a ':E nvim'
abbr -a ':e nvim'
abbr -a 'bandle bundle install --jobs=5 --path=vendor/bundle'
abbr -a 'be bundle exec'
abbr -a 'cask brew cask'
abbr -a 'cl clear'
abbr -a 'd dirh'
abbr -a 'fig docker-compose'
abbr -a 'g git'
abbr -a 'ga git add'
abbr -a 'gaa git add --all .'
abbr -a 'gac git add --all .; and git commit'
abbr -a 'gacm git add --all .; and git commit -m'
abbr -a 'gc git commit'
abbr -a 'gcam git commit --amend -m'
abbr -a 'gcm git commit -m'
abbr -a 'gd git diff'
abbr -a 'gg ag'
abbr -a 'gpr git pull --rebase'
abbr -a 'hi hicat -N'
abbr -a 'l ls'
abbr -a 'macdown open -a MacDown.app'
abbr -a 'n npm'
abbr -a 'nr npm run'
abbr -a 'nt npm test'
abbr -a 'nv nvim'
abbr -a 'sha256 shasum -a 256'
abbr -a 't timetip'
abbr -a 'ta tmux attach'
abbr -a 'tigs tig status'
abbr -a 'v nvim'
abbr -a 'vim nvim'
