abbr -a 'g git'
abbr -a 'l ls'
abbr -a 'ta tmux attach'
abbr -a 'gc git commit'
abbr -a 'tigs tig status'
abbr -a 'nv nvim'
abbr -a 'nt npm test'
abbr -a 'gaa git add --all .'
abbr -a 'ga git add'
abbr -a 'gpr git pull --rebase'
abbr -a 'cask brew cask'
abbr -a 'vim nvim'
abbr -a 'gcm git commit -m'
abbr -a 'd dirh'
abbr -a '1 prevd'
abbr -a '2 nextd'
abbr -a 'hi hicat -N'
abbr -a 'gg ag'
abbr -a 'be bundle exec'
abbr -a 't timetip'
abbr -a 'gac git add --all .; and git commit'
abbr -a 'gacm git add all .; and git commit -m'
abbr -a 'macdown open -a MacDown.app'
