#!/usr/bin/env sh
if [ -z "$1" ]; then
  echo "Usage:"
  echo "  gh-clone repo"
  echo "  gh-clone user/repo"
  exit 1
fi

repo="$1"
if ! echo "$repo" | grep / > /dev/null; then
  user="$(git config github.user)"
  repo="${user}/${repo}"
fi

git clone https://github.com/${repo}.git
