#!/usr/bin/env bash
# Forks the current repository.
#
#     $ git clone https://github.com/docker/compose.git
#     $ cd compose
#     $ git-forkthis
#
#       Forking docker/compose to rstacruz/compose...
#
#           upstream  https://github.com/docker/compose.git
#             origin  https://github.com/rstacruz/compose.git
#
#       See: https://github.com/rstacruz/compose
#
source ${0%/*}/git-utils.sh

case "$1" in
  -h|--help)
    echo "Usage: $(basename ${0})"
    echo "Forks the current project in GitHub."
    exit
    ;;
esac

user=$(github_username)
password=$(github_password)
repo=$(github_repo)
project=$(github_project)

# Remote URLs
upstream=$(git config --get remote.origin.url)
url="https://github.com/${user}/${project}"
origin="${url}.git"

if [ "$repo" = "$user/$project" ]; then
  die "$repo is already your project."
fi

echo "Forking $repo to $user/$project..."
output=$(curl -s -X POST -u "$user:$password" "https://api.github.com/repos/$repo/forks")
if [ $? != 0 ]; then die "curl failed"; fi
if ! (echo $output | grep full_name >/dev/null); then
  echo $output
  die "curl failed"
fi

echo ""
echo "    upstream  $upstream"
git remote add upstream "$upstream"
if [ $? != 0 ]; then die "failed to add upstream"; fi

git remote rm origin
echo "      origin  $origin"
git remote add origin "$origin"

echo ""
echo "See: $url"
