#!/usr/bin/env sh

# jekyll-new-post:
# Creates a new post.
#
#     jekyll-new-post creating stuff
#     #=> vim 2015-05-27-creating-stuff.md

name=`echo $* | tr [:upper:] [:lower:] | sed 's/ /-/g'`
fname="`date +%Y-%m-%d`-$name.md"
if [ ! -f $fname ]; then
  echo "---" > $fname
  echo "title: $*" >> $fname
  echo "description: ..." >> $fname
  echo "tags: []" >> $fname
  echo "---" >> $fname
fi
${EDITOR:-vim} $fname
