set -U fish_color_error red '--italic'
set -U fish_color_escape 'yellow'
set -U fish_color_operator 'yellow'
set -U fish_color_param 'brcyan'
set -U fish_color_quote 'brblue'
set -U fish_color_redirection 'yellow'
set -U fish_color_status 'brcyan'
set -U fish_color_autosuggestion 'brblack'
set -U fish_color_end 'brcyan'
set -U fish_color_user 'brcyan'
set -U fish_color_command '--bold'
set -U fish_color_comment 'brcyan'
